language: node_js
node_js:
- stable
sudo: false
services:
  - mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g mocha
- npm install -g backbone
- npm install -g socket.io-client
- npm install
script:
- npm test
- npm run coverage
